apiVersion: v1
kind: Pod
metadata:
  name: ps-svc
spec:
  containers:
  - name: busybox
    image: busybox:stable
    command: ['sh', '-c', 'while true; do echo Running...; sleep 5; done']
    resources:
      requests:
        cpu: "10m"
        memory: "2Gi"
      limits:
        cpu: "20m"
        memory: "10Mi"
